# Remove generated previews from building the CV for PRs
name: cv-cleanup

on:
  pull_request:
    types:
      - closed

permissions: {}

jobs:
  clean_branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Need to persist credentials so we delete a branch
          persist-credentials: true

      - name: Delete the CV preview branch
        # Allow this to fail if there is no branch to delete
        continue-on-error: true
        run: |
          git push origin --delete "preview-pr${{ github.event.number }}"
