# Comment on the PR with a link to a preview of the CV
name: cv-preview-comment

on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      PREVIEW_BRANCH: preview-pr${{ github.event.number }}
    steps:
      - name: Create comment with preview link
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peter-evans/create-or-update-comment@9f28a7d0f315487b1a02f09988ddb322a0212673
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            :robot: :wave: Hi there, human. It looks like you're editing the CV. I'll build it for you whenever you make changes and place the resulting PDF at: https://github.com/${{ github.repository }}/blob/${{ env.PREVIEW_BRANCH }}/cv.pdf

            > The preview branch `${{ env.PREVIEW_BRANCH }}` will be deleted when the PR is closed/merged.
          comment-author: "github-actions[bot]"
