name: Deploy CV

on:
  push:
    branches: [ master ]


jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt install make pandoc wkhtmltopdf

    - name: Build CV (pdf and html)
      run: |
        xvfb-run --auto-servernum make pdf
        xvfb-run --auto-servernum make pdf_es
        xvfb-run --auto-servernum make html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: _build
